apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkstoreservice
  labels:
    app: linkstoreservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkstoreservice
  template:
    metadata:
      labels:
        app: linkstoreservice
    spec:
      containers:
      - name: linkstoreservice
        image: alican/linkstoreservice:0.1
        ports:
        - containerPort: 8100
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/actuator/info"
            port: 8100
            scheme: "HTTP"
          initialDelaySeconds: 25
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet: 
            path: "/actuator/health"
            port: 8100
            scheme: "HTTP"
          initialDelaySeconds: 25
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: linkstoreservice
  labels:
    app: linkstoreservice
    spring-boot: "true"
spec:
  ports:
  - port: 8100
    protocol: TCP
  selector:
    app: linkstoreservice
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linkstoreservice
data:
  application.yml: |-
    spring.datasource.url: jdbc:mariadb://vested-poodle-mariadb/cs443
    spring.datasource.username: root
    spring.datasource.password: UOZmH5SD63
